import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Ragul',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality shirt',
    },
    {
      // _id: '4',
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Formal Shoe',
      slug: 'formal-shoe',
      category: 'Shoes',
      image: '/images/shoe1.jpg',
      price: 100,
      countInStock: 10,
      brand: 'Zarman',
      rating: 4.0,
      numReviews: 15,
      description: 'high quality shoe',
    },
    {
      name: 'New Balance Shoe',
      slug: 'new-balance-shoe',
      category: 'Shoes',
      image: '/images/shoe2.jpg',
      price: 200,
      countInStock: 10,
      brand: 'New Balance',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality shoe',
    },
    {
      name: 'Puma Sports Shoe',
      slug: 'puma-sports-shoe',
      category: 'Shoes',
      image: '/images/shoe3.jpg',
      price: 100,
      countInStock: 10,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 25,
      description: 'high quality shoe',
    },

    {
      name: 'Puma Casual Shoe',
      slug: 'puma-casula-shoe',
      category: 'Shoes',
      image: '/images/shoe4.jpg',
      price: 100,
      countInStock: 10,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 35,
      description: 'high quality shoe',
    },
  ],
};
export default data;
